### ISSUE TITLE
Unlock "Pair Extraordinaire" for ifefrost

### ISSUE THREAD

**Issue by ifefrost** [Prakash4844/Get-Pair-Extraordinaire#100]
Name:  ifefrost
Email: temiladeladipo@hotmail.com

**Comment by Prakash4844** [comment]
Hi @ifefrost,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #101
Thank you for your contribution.

Please star the repository if you liked it.
