### ISSUE TITLE
Unlock "Pair Extraordinaire" for the-1Riddle

### ISSUE THREAD

**Issue by the-1Riddle** [Prakash4844/Get-Pair-Extraordinaire#102]
Name: the-1Riddle
Email: elv.s.earl@gmail.com

**Comment by Prakash4844** [comment]
Hi @the-1Riddle,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #103
Thank you for your contribution.

Please star the repository if you liked it.

**Comment by the-1Riddle** [comment]
> Hi @the-1Riddle,
> 
> Process has been started for your request.
> 
> Thank you for using Get Pair Extraordinaire! 😄

Thank you and welcome ^_^
