### ISSUE TITLE
Unlock "Pair Extraordinaire" for  AdityaNow

### ISSUE THREAD

**Issue by AdityaNow** [Prakash4844/Get-Pair-Extraordinaire#104]
Name: Aditya Mali
Email: adityamali1208@gmail.com

**Comment by Prakash4844** [comment]
Hi @AdityaNow,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #105
Thank you for your contribution.

Please star the repository if you liked it.
