### ISSUE TITLE
Unlock "Pair Extraordinaire" for ternera

### ISSUE THREAD

**Issue by ternera** [Prakash4844/Get-Pair-Extraordinaire#112]
Name: ternera
Email: contact@ternera.org

**Comment by Prakash4844** [comment]
Hi @ternera,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #113
Thank you for your contribution.

Please star the repository if you liked it.
