### ISSUE TITLE
Unlock "Pair Extraordinaire" for sawmodz

### ISSUE THREAD

**Issue by sawmodz** [Prakash4844/Get-Pair-Extraordinaire#116]
Name: sawmodz
Email: theowincke@live.fr

**Comment by Prakash4844** [comment]
Hi @sawmodz,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #117
Thank you for your contribution.

Please star the repository if you liked it.
