### ISSUE TITLE
Pair Extraordinaire request

### ISSUE THREAD

**Issue by lohith8776** [Prakash4844/Get-Pair-Extraordinaire#126]
Name: Lohith
Email: lohithstark001@gmail.com

**Comment by Prakash4844** [comment]
Hi @lohith8776,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #127
Thank you for your contribution.

Please star the repository if you liked it.
