### ISSUE TITLE
Pair Extraordinaire request

### ISSUE THREAD

**Issue by Vaathii** [Prakash4844/Get-Pair-Extraordinaire#128]
Name: SivaShankar
Email: friends@shivashankar.fun

**Comment by Prakash4844** [comment]
Already done, 
<img width="446" alt="image" src="https://github.com/Prakash4844/Get-Pair-Extraordinaire/assets/81550376/f042eba1-f460-44ec-b2e9-55d4f786e1b3">


Closing...
