### ISSUE TITLE
Unlock "Pair Extraordinaire" for It'z RJ

### ISSUE THREAD

**Issue by itz-rj-here** [Prakash4844/Get-Pair-Extraordinaire#135]
Name: It'z RJ
Email: faiadmahmudadil@gmail.com

**Comment by Prakash4844** [comment]
Hi @itz-rj-here,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #136
Thank you for your contribution.

Please star the repository if you liked it.
