### ISSUE TITLE
Unlock "Pair Extraordinaire" for Ankan Pal

### ISSUE THREAD

**Issue by itsyourap** [Prakash4844/Get-Pair-Extraordinaire#139]
Name: Ankan Pal
Email: itsyourap@gmail.com

**Comment by Prakash4844** [comment]
Hi @itsyourap,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #140
Thank you for your contribution.

Please star the repository if you liked it.
