### ISSUE TITLE
Unlock "Pair Extraordinaire" for Akash-Singh04

### ISSUE THREAD

**Issue by Akash-Singh04** [Prakash4844/Get-Pair-Extraordinaire#141]
Name:Akash-Singh04 
Email:akashsingh2210670@gmail.comm

**Comment by Prakash4844** [comment]
Hi @Akash-Singh04,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #142
Thank you for your contribution.

Please star the repository if you liked it.
