### ISSUE TITLE
Unlock "Pair Extraordinaire" for {@Matt0967}

### ISSUE THREAD

**Issue by Matt0967** [Prakash4844/Get-Pair-Extraordinaire#147]
Name: @Matt0967
Email: perezmatthieu1@gmail.com

**Comment by Prakash4844** [comment]
Hi @Matt0967,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #148
Thank you for your contribution.

Please star the repository if you liked it.
