### ISSUE TITLE
Unlock "Pair Extraordinaire" for ishubarman7

### ISSUE THREAD

**Issue by ishubarman7** [Prakash4844/Get-Pair-Extraordinaire#149]
Name: Ishu Barman 
Email: ishu.barman9067900@gmail.com

**Comment by Prakash4844** [comment]
Hi @ishubarman7,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #150
Thank you for your contribution.

Please star the repository if you liked it.
