### ISSUE TITLE
Unlock "Pair Extraordinaire" for Nujan Sitaula

### ISSUE THREAD

**Issue by NujanSitaula** [Prakash4844/Get-Pair-Extraordinaire#159]
Name: Nujan Sitaula
Email: nujan.sitaula@outlook.com

**Comment by Prakash4844** [comment]
Hi @NujanSitaula,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #160
Thank you for your contribution.

Please star the repository if you liked it.
