### ISSUE TITLE
Unlock "Pair Extraordinaire" for alexis-coulombe

### ISSUE THREAD

**Issue by alexis-coulombe** [Prakash4844/Get-Pair-Extraordinaire#16]
Name: alexis-coulombe
Email: alexis.410@hotmail.com

**Comment by Prakash4844** [comment]
Hi @alexis-coulombe,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #17
