### ISSUE TITLE
Unlock "Pair Extraordinaire" for _MR1_

### ISSUE THREAD

**Issue by Marouane-Elgoumiri** [Prakash4844/Get-Pair-Extraordinaire#172]
Name: _MR1_
Email: mar.elgoumiri@hotmail.com

**Comment by Prakash4844** [comment]
Hi @Marouane-Elgoumiri,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #173
Thank you for your contribution.

Please star the repository if you liked it.
