### ISSUE TITLE
Unlock "Pair Extraordinaire" for Dom Luther

### ISSUE THREAD

**Issue by domluther** [Prakash4844/Get-Pair-Extraordinaire#189]
Name: Dom Luther
Email: d.luther@gmail.com

**Comment by Prakash4844** [comment]
Hi @domluther,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #190
Thank you for your contribution.

Please star the repository if you liked it.
