### ISSUE TITLE
Unlock "Pair Extraordinaire" for Nigh Fury

### ISSUE THREAD

**Issue by hotcoding85** [Prakash4844/Get-Pair-Extraordinaire#195]
Name: Night Fury
Email: hotcoding85@gmail.com

**Comment by Prakash4844** [comment]
Hi @hotcoding85,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #198
Thank you for your contribution.

Please star the repository if you liked it.
