### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Manishak798}

### ISSUE THREAD

**Issue by Manishak798** [Prakash4844/Get-Pair-Extraordinaire#20]
Name: Manisha Kundnani
Email: monakundnani113@gmail.com

**Comment by Manishak798** [comment]
added new issue

**Comment by Prakash4844** [comment]
Hi @Manishak798,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #21
Thank you for your contribution.

Please star the repository if you liked it.
