### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Your_Name}

### ISSUE THREAD

**Issue by sethshivam11** [Prakash4844/Get-Pair-Extraordinaire#204]
Name: Shivam Soni
Email: legendshivam11@gmail.com

**Comment by Prakash4844** [comment]
Hi @sethshivam11,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #205
Thank you for your contribution.

Please star the repository if you liked it.

**Comment by Prakash4844** [comment]
It seems [legendshivam11@gmail.com](mailto:legendshivam11@gmail.com) is not your primary email. could you recheck?

**Comment by sethshivam11** [comment]
@Prakash4844 Yes, I am sure that it is my email.
