### ISSUE TITLE
Unlock "Pair Extraordinaire" for {LeleDallas}

### ISSUE THREAD

**Issue by LeleDallas** [Prakash4844/Get-Pair-Extraordinaire#22]
Name: LeleDallas
Email: emanuele.dallara@studio.unibo.it

**Comment by Prakash4844** [comment]
Hi @LeleDallas,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #23
Thank you for your contribution.

Please star the repository if you liked it.
