### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Subrata Jana}

### ISSUE THREAD

**Issue by SpectraX07** [Prakash4844/Get-Pair-Extraordinaire#224]
Name: Subrata Jana
Email: webwanderer007@gmail.com

**Comment by Prakash4844** [comment]
Hi @SpectraX07,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #225
Thank you for your contribution.

Please star the repository if you liked it.
