### ISSUE TITLE
Unlock "Pair Extraordinaire" for kamdz

### ISSUE THREAD

**Issue by kamdz** [Prakash4844/Get-Pair-Extraordinaire#240]
Name: kamdz
Email: github@kamdz.dev

**Comment by Prakash4844** [comment]
Hi @kamdz,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #241
Thank you for your contribution.

Please star the repository if you liked it.
