### ISSUE TITLE
Unlock "Pair Extraordinaire" for DARKDRAGON_LK

### ISSUE THREAD

**Issue by DARKDRAGON-LK** [Prakash4844/Get-Pair-Extraordinaire#258]
Name: Lawan Samarasekara
Email: lawan.chaamindu1234@gmail.com

**Comment by Prakash4844** [comment]
Hi @DARKDRAGON-LK,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #259
Thank you for your contribution.

Please star the repository if you liked it.
