### ISSUE TITLE
Improve workflow to only run when there is a suitable PR

### ISSUE THREAD

**Issue by Prakash4844** [Prakash4844/Get-Pair-Extraordinaire#26]
Add a PR check before checking out repository, in Pair-Extraordinaire.yml, so that it only fire up py script when there is a PR available with `request` label.

This will improve workflow execution time in case of no suitable PR is available.

**Comment by Prakash4844** [comment]
Now we wait for someone to create an issue.

**Comment by tdemin** [comment]
@Prakash4844 worked as advertised on #27 :)

**Comment by Prakash4844** [comment]
Hey @tdemin, thanks for helping me test it out. 😊

Stay awesome.
