### ISSUE TITLE
Unlock "Pair Extraordinaire" for Markichu

### ISSUE THREAD

**Issue by Markichu** [Prakash4844/Get-Pair-Extraordinaire#29]
Name: Markichu
Email: fox.marcus1887@gmail.com

**Comment by Prakash4844** [comment]
Hi @Markichu,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #30
Thank you for your contribution.

Please star the repository if you liked it.
