### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Your_Name}

### ISSUE THREAD

**Issue by Matyu9** [Prakash4844/Get-Pair-Extraordinaire#35]
Name: matyu9
Email: degueurce.mathieu@gmail.com

**Comment by Prakash4844** [comment]
Hi @Matyu9,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #36
Thank you for your contribution.

Please star the repository if you liked it.
