### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Chantal}

### ISSUE THREAD

**Issue by mademoiselle-chantal** [Prakash4844/Get-Pair-Extraordinaire#37]
Name: <Chantal>
Email: <chantalmunashechicheko@gmail.com>

**Comment by Prakash4844** [comment]
Hi @mademoiselle-chantal,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #38
Thank you for your contribution.

Please star the repository if you liked it.

**Comment by mademoiselle-chantal** [comment]
Thank you @Prakash4844
