### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Pavel}

### ISSUE THREAD

**Issue by PavelMal** [Prakash4844/Get-Pair-Extraordinaire#39]
Name: Pavel
Email: lifokok697@poverts.com

**Comment by Prakash4844** [comment]
Hi @PavelMal,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #40
Thank you for your contribution.

Please star the repository if you liked it.

**Comment by Prakash4844** [comment]
Hey @PavelMal, It seems the Email ID you've provided is not you primary email of GitHub, see the Readme.

See this to find out your correct email: https://github.com/Prakash4844/Get-Pair-Extraordinaire/blob/main/README.md#how-to-use
