### ISSUE TITLE
Unlock "Pair Extraordinaire" for Konjo Tech

### ISSUE THREAD

**Issue by konjotech** [Prakash4844/Get-Pair-Extraordinaire#43]
Name: Konjo Tech
Email: konjo@konjotech.com

**Comment by Prakash4844** [comment]
Hi @konjotech,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #44
Thank you for your contribution.

Please star the repository if you liked it.
