### ISSUE TITLE
Unlock "Pair Extraordinaire" for {Your_Name}

### ISSUE THREAD

**Issue by Navid-Rahman** [Prakash4844/Get-Pair-Extraordinaire#46]
Name: Unloack Pair Extraordinaire request
Email: navidrahman92@gmail.com

**Comment by Prakash4844** [comment]
Hi @Navid-Rahman,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #47
Thank you for your contribution.

Please star the repository if you liked it.
