### ISSUE TITLE
Unlock "Pair Extraordinaire" for Xabierland

### ISSUE THREAD

**Issue by Xabierland** [Prakash4844/Get-Pair-Extraordinaire#60]
Name: Xabierland
Email: xabierland@gmail.com

**Comment by Prakash4844** [comment]
Hey, it seems your email is not getting parsed properly. I will see what can be done.

**Comment by Prakash4844** [comment]
Hi @Xabierland,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #61
Thank you for your contribution.

Please star the repository if you liked it.
