### ISSUE TITLE
Unlock "Pair Extraordinaire" for Manik

### ISSUE THREAD

**Issue by manik-007** [Prakash4844/Get-Pair-Extraordinaire#76]
Name: Manik
Email: manik23265@gmail.com

**Comment by Prakash4844** [comment]
Hi @manik-007,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #77
Thank you for your contribution.

Please star the repository if you liked it.
