### ISSUE TITLE
Pair Extraordinaire request

### ISSUE THREAD

**Issue by applesm18** [Prakash4844/Get-Pair-Extraordinaire#80]
Name: applesm18
Email: applesm18@gmail.com

**Comment by Prakash4844** [comment]
Hi @applesm18,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #81
Thank you for your contribution.

Please star the repository if you liked it.
