### ISSUE TITLE
Unlock "Pair Extraordinaire" for {SakuraBlossomTree}

### ISSUE THREAD

**Issue by SakuraBlossomTree** [Prakash4844/Get-Pair-Extraordinaire#96]
Name: SakuraBlossomTree
Email:yohib.hussain@gmail.com

**Comment by Prakash4844** [comment]
Hi @SakuraBlossomTree,

Process has been started for your request.

Thank you for using Get Pair Extraordinaire! :smile:

**Comment by Prakash4844** [comment]
Your Request has been processed in PR #97
Thank you for your contribution.

Please star the repository if you liked it.
